export type Article = {
    id: string;
    title: string;
    summary: string;
    author: string;
    authorId: string | null;
    likes: number | null;
    topic: string;
    retainedForHistory?: boolean | undefined;
    curation?: {
        why: string;
        readingGuide: string;
        caveat: string;
        reviewedAt: string;
    } | undefined;
    authorUrl?: string | null | undefined;
    url?: string | undefined;
    avatar?: string | undefined;
    badge?: string | undefined;
    sourceKind?: "zhihu" | "web" | "upload" | "collection" | "creation" | undefined;
    materialId?: string | undefined;
    site?: string | undefined;
    badgeIcon?: string | undefined;
    commentCount?: number | undefined;
    editedAt?: number | undefined;
    contentType?: string | undefined;
    contentId?: string | undefined;
    authorityLevel?: string | undefined;
    rankingScore?: number | undefined;
    comments?: string[] | undefined;
    authorSignature?: string | undefined;
};
export type AuthorEvidence = {
    id: string;
    name: string;
    expertise: string;
    evidenceId: string;
    authorUrl?: string | null | undefined;
    likes?: number | undefined;
    url?: string | undefined;
    avatar?: string | undefined;
    badge?: string | undefined;
    sourceKind?: "zhihu" | "web" | undefined;
    site?: string | undefined;
    badgeIcon?: string | undefined;
    commentCount?: number | undefined;
    editedAt?: number | undefined;
    contentType?: string | undefined;
    contentId?: string | undefined;
    authorityLevel?: string | undefined;
    rankingScore?: number | undefined;
    comments?: string[] | undefined;
    authorSignature?: string | undefined;
    matchReason?: string | undefined;
    coverageLimit?: string | undefined;
};
export type GraphNode = {
    type: "author" | "custom" | "root" | "article" | "answer";
    id: string;
    title: string;
    text: string;
    sources: string[];
    parents: string[];
    author?: {
        id: string;
        name: string;
        expertise: string;
        evidenceId: string;
        authorUrl?: string | null | undefined;
        likes?: number | undefined;
        url?: string | undefined;
        avatar?: string | undefined;
        badge?: string | undefined;
        sourceKind?: "zhihu" | "web" | undefined;
        site?: string | undefined;
        badgeIcon?: string | undefined;
        commentCount?: number | undefined;
        editedAt?: number | undefined;
        contentType?: string | undefined;
        contentId?: string | undefined;
        authorityLevel?: string | undefined;
        rankingScore?: number | undefined;
        comments?: string[] | undefined;
        authorSignature?: string | undefined;
        matchReason?: string | undefined;
        coverageLimit?: string | undefined;
    } | undefined;
    color?: string | undefined;
    stroke?: number | undefined;
    origin?: "author" | "articles" | "direct" | undefined;
    basisId?: string | undefined;
    edited?: boolean | undefined;
};
