import {SourceComments} from './SourceComments'
import {SourceReading,useSourcePresentation} from './SourcePresentation'
import { MarkdownMath } from '../lib/MarkdownMath'
import { useLearningData } from './data'
import { useState } from 'react'
import { type Article, type Phase } from './model'
import { Avatar, CountBadge, Glyph, IconButton, StatusPill } from './atoms'
export function ArticleCard({ article, selected=false, onOpen, onToggle, onAuthor }: { article:Article; selected?:boolean; onOpen?:()=>void; onToggle?:()=>void;onAuthor?:(id:string)=>void }) { const {articles,example}=useLearningData(); const {value}=useSourcePresentation(article.url,!example&&!article.avatar);
  return <article role="listitem" className={`lp-article-card ${selected?'is-selected':''}`}>
    <button className="lp-article-main" aria-label={`阅读 ${article.title}`} onClick={onOpen}><div className="lp-article-title"><span className="lp-article-index">{articles.findIndex(a=>a.id===article.id)+1}</span><h3>{article.title}</h3></div><MarkdownMath source={article.curation?.why??article.summary.split('\n\n')[0]} className="lp-article-excerpt" sourceExcerpt={article.sourceKind!=='upload'} passive/></button>
    <footer className="lp-article-footer">
      <div className="lp-article-meta">{(article.sourceKind==='web'||article.sourceKind==='upload')?<Glyph name="document" size={18}/>:<Avatar author src={article.avatar||value?.data.metadata.avatar} size={20}/>}<span className="lp-source-author-name" title={article.author}>{article.author}</span><span className="lp-meta-dot">·</span><span className="lp-source-topic">{article.topic}</span>{article.likes!==null&&<span className="lp-likes"><Glyph name="like" size={13}/>{article.likes.toLocaleString()}</span>}</div>
      {article.authorId&&onAuthor&&<button className="lp-article-author-link" onClick={()=>onAuthor(article.authorId!)}><Glyph name="graph" size={13}/>作者足迹</button>}
    </footer>
    <button className="lp-article-select" aria-label={`${selected?'取消引用':'引用'} ${article.title}`} aria-pressed={selected} onClick={onToggle}><Glyph name={selected?'check':'plus'} size={14}/><span>{selected?'已引用':'引用'}</span></button>
  </article>
}
export function ArticleDetail({ article, onBack, onAuthor }: { article:Article; onBack?:()=>void; onAuthor?:(id:string)=>void }) { const {example}=useLearningData();const {value}=useSourcePresentation(article.url,!example&&!article.avatar);return <div className="lp-detail lp-enter" key={article.id}><button className="lp-text-button lp-back-results" onClick={onBack}><Glyph name="back" size={15}/>返回检索结果</button><div className="lp-detail-content"><div className="lp-eyebrow">{example?'示例来源':article.sourceKind==='upload'?'我的资料':article.sourceKind==='web'?(article.site??'全网资料'):'知乎'} · {article.topic}</div><h2>{article.title}</h2><div className="lp-detail-author">{(article.sourceKind==='web'||article.sourceKind==='upload')?<Glyph name="document" size={30}/>:<Avatar author src={article.avatar||value?.data.metadata.avatar} size={38}/>}<div className="lp-detail-author-info"><strong>{article.author}{article.badgeIcon&&<img className="lp-author-badge-icon" src={article.badgeIcon} alt={article.badge??"知乎认证"} referrerPolicy="no-referrer"/>}</strong><span className="lp-detail-author-description">{article.sourceKind==='upload'?(article.topic==='PDF 总结'?'PDF 内容总结':'文件正文'):'文章内容总结'}{article.badge?` · ${article.badge}`:''}</span>{article.authorId&&onAuthor&&<button type="button" className="lp-detail-author-action" onClick={()=>onAuthor(article.authorId!)}><Glyph name="graph" size={14}/>查看作者与学习足迹</button>}</div>{article.likes!==null&&<span className="lp-likes"><Glyph name="like" size={15}/>{article.likes.toLocaleString()} 赞同</span>}</div>{(article.editedAt||article.commentCount!==undefined)&&<div className="lp-source-facts">{article.editedAt&&<span>更新于 {new Date(article.editedAt*1000).toLocaleDateString('zh-CN')}</span>}{article.commentCount!==undefined&&<span>{article.commentCount.toLocaleString()} 条评论</span>}</div>}<div className="lp-detail-body">{article.sourceKind==='upload'?<MarkdownMath source={article.summary}/>:<SourceReading allowPresentation={!example} source={article.summary} url={article.url} curated={example?article.curation?.readingGuide:undefined}/>}</div><SourceComments allowPresentation={!example} comments={article.comments} total={article.commentCount} url={article.url}/>{article.url&&!article.url.startsWith('https://zhihu-demo.invalid/')?<a className="lp-original" href={article.url} target="_blank" rel="noopener noreferrer">{article.sourceKind==='web'?'前往来源网站阅读原文':'去知乎阅读原文'}<Glyph name="link" size={15}/></a>:article.url?<p className="lp-detail-note">演示资料 · 用于体验收藏学习流程</p>:null}<div className="lp-detail-note"><Glyph name="eye" size={14}/>{example?'示例阅读材料':'这份资料已作为本次提问材料'}</div></div></div> }
export function ArticlePanel({ phase='ready', detail, selected, onOpen, onBack, onToggle, onRetry, canRetry=true, onAuthor }: { phase?:Phase; detail:string|null; selected:string[]; onOpen:(id:string)=>void; onBack:()=>void; onToggle:(id:string)=>void; onRetry:()=>void;canRetry?:boolean;onAuthor?:(id:string)=>void }) { const {articles,concept:CONCEPT}=useLearningData();
  const [sort,setSort]=useState('relevance')
  if(detail) { const a=articles.find(a=>a.id===detail); if(a)return <ArticleDetail article={a} onBack={onBack} onAuthor={onAuthor}/> }
  const items=sort==='likes'?[...articles].sort((a,b)=>(b.likes??-1)-(a.likes??-1)):sort==='recent'?[...articles].sort((a,b)=>(b.editedAt??0)-(a.editedAt??0)):articles
  return <div className="lp-article-panel"><div className="lp-source-heading"><Glyph name="search" size={17}/><h2>{CONCEPT}</h2></div><div className="lp-search-tools"><span>相关内容 <CountBadge>{articles.length|| (phase==='searching'?'—':0)}</CountBadge></span><label className="lp-sort"><select aria-label="文章排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="relevance">最相关</option><option value="likes">点赞最多</option><option value="recent">最近更新</option></select><Glyph name="chevron" size={13}/></label></div>
  {phase==='searching'&&!articles.length?<div className="lp-search-loading"><StatusPill busy>正在寻找这个概念的相关内容</StatusPill><p>从不同问法出发，等三路搜索完成后一起呈现</p>{[1,2,3,4].map(n=><div className="lp-skeleton-card" key={n}><i/><i/><i/></div>)}</div>:(phase==='empty'||phase==='search-error')&&!articles.length?<div className="lp-empty-state"><Glyph name="search" size={30}/><h3>{phase==='empty'?'暂未找到相关内容':'还有一路搜索未完成'}</h3><p>{phase==='empty'?'可以重新搜索。找到相关内容后，我们再开始讲解。':'成功返回的材料已经保留，可以重试失败的搜索。'}</p><button className="lp-secondary" disabled={!canRetry} onClick={onRetry}><Glyph name="refresh" size={15}/>重新搜索</button></div>:<div className="lp-article-scroll" role="list" aria-label="本次学习资料">{items.map(a=><ArticleCard key={a.id} article={a} onAuthor={onAuthor} selected={selected.includes(a.id)} onOpen={()=>onOpen(a.id)} onToggle={()=>onToggle(a.id)}/>)}<p className="lp-list-end">{phase==='searching'?'已添加资料可先阅读，正在整理相关内容':'本次学习资料已全部展示'}</p></div>}</div>
}
