import {sourceLink} from './source-link'
import { SendControl } from '../components/SendControl'
import {paragraphsMarkdown} from '@threadpeak/contracts/learning-markdown'
import type {TaskView} from './client'
import type {TaskActivity} from '@threadpeak/contracts/task-activity'
import { MarkdownMath } from '../lib/MarkdownMath'
import { useLearningData } from './data'
import { useEffect, useRef, useState } from 'react'
import { type Conversation, type GraphNode, type Message, type Paragraph, type Phase } from './model'
import { Avatar, Glyph, IconButton, SourceTag, StatusPill } from './atoms'
export function ContextChips({ selected, nodes, onRemove, onClear }: {selected:string[];nodes:GraphNode[];onRemove?:(id:string)=>void;onClear?:()=>void}) { return <div className="lp-context" aria-label="当前提问材料"><Glyph name="eye" size={15}/>{selected.length===0?<span>{nodes.some(n=>n.type==='article')?'全部资料':'材料尚未就绪'} <small>{nodes.filter(n=>n.type==='article').length} 篇</small></span>:<><div className="lp-context-items">{selected.map(id=>{const node=nodes.find(n=>n.id===id);return <span className="lp-context-chip" key={id} title={node?.title}><Glyph name={node?.type==='article'?'book':'graph'} size={12}/><span>{node?.title??id}</span><button aria-label={`移除材料 ${node?.title??id}`} onClick={()=>onRemove?.(id)}><Glyph name="close" size={11}/></button></span>})}</div><button className="lp-context-clear" onClick={onClear}>清除</button></>}</div> }
export function LearningComposer({ selected=[], nodes=[], onRemove, onClear, depth='fast', onDepth, onSend, onStop, busy=false, disabled=false, paused=false, mode='ai', onMode, focusToken=0 }: {selected?:string[];nodes?:GraphNode[];onRemove?:(id:string)=>void;onClear?:()=>void;depth?:'fast'|'deep';onDepth?:(depth:'fast'|'deep')=>void;onSend?:(text:string)=>Promise<boolean>;onStop?:()=>void;busy?:boolean;disabled?:boolean;paused?:boolean;mode?:'ai'|'author';onMode?:(mode:'ai'|'author')=>void;focusToken?:number}) {
  const [value,setValue]=useState(''),[menu,setMenu]=useState(false),[submitting,setSubmitting]=useState(false);const sending=useRef(false);const input=useRef<HTMLTextAreaElement>(null)
  useEffect(()=>{if(focusToken)input.current?.focus()},[focusToken])
  const send=async()=>{if(!value.trim()||busy||disabled||paused||sending.current)return;const sent=value;sending.current=true;setSubmitting(true);try{if(await onSend?.(sent.trim()))setValue(v=>v===sent?'':v)}finally{sending.current=false;setSubmitting(false)}}
  return <div className={`lp-composer ${mode==='author'?'is-author':''}`}><ContextChips selected={selected} nodes={nodes} onRemove={onRemove} onClear={onClear}/>{mode==='author'&&<div className="lp-author-mode"><Glyph name="message" size={13}/>向博主提问<button onClick={()=>onMode?.('ai')} aria-label="退出问博主"><Glyph name="close" size={12}/></button></div>}<textarea ref={input} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}} placeholder={mode==='author'?'想听听博主怎样理解这个问题？':'继续提问，探索这个概念…'} aria-label={mode==='author'?'向博主提问':'学习提问'} disabled={disabled}/><div className="lp-composer-bottom"><div className="lp-depth-wrap"><button className="lp-depth" onClick={()=>setMenu(!menu)} aria-expanded={menu}><Glyph name="spark" size={15}/>{depth==='deep'?'深度思考':'快速回答'}<Glyph name="chevron" size={12}/></button>{menu&&<><button className="lp-menu-dismiss" aria-label="关闭思考深度菜单" onClick={()=>setMenu(false)}/><div className="lp-depth-menu" role="menu">{(['fast','deep'] as const).map(d=><button key={d} role="menuitemradio" aria-checked={d===depth} onClick={()=>{onDepth?.(d);setMenu(false)}}><Glyph name={d==='fast'?'spark':'layers'} size={17}/><span><strong>{d==='fast'?'快速回答':'深度思考'}</strong><small>{d==='fast'?'直接说明，快速理解':'多想一步，仔细推敲'}</small></span>{d===depth&&<Glyph name="check" size={15}/>}</button>)}</div></>}</div><span className="lp-composer-hint">Shift + Enter 换行</span><SendControl busy={busy} submitting={submitting} disabled={!value.trim()||disabled||paused} onSend={()=>void send()} onStop={onStop} sendLabel="发送问题"/></div></div>
}
export function AnswerMessage({ message, onSource, onNode, onCopy }: {message:Message;onSource?:(id:string)=>void;onNode?:(id:string)=>void;onCopy?:(text:string)=>void}) { const {articles}=useLearningData();
  if(message.role==='user')return <div className="lp-user-message">{message.selected?.length?<div className="lp-message-materials"><Glyph name="book" size={12}/>{message.selected.length} 项引用材料</div>:null}<p>{message.text}</p></div>
  return <article className={`lp-answer ${message.kind==='author'?'lp-author-answer':''}`}><Avatar author={message.kind==='author'} size={33}/><div className="lp-answer-content"><div className="lp-answer-name">{message.kind==='author'?`找到 ${message.paragraphs?.filter(p=>p.author).length??0} 位新博主`:'刘看山'}<span>{message.kind==='author'?'来自问博主':'陪你一起理解'}</span></div>{message.paragraphs?.map(p=><section className="lp-answer-section" key={p.id} data-answer-node={p.id}><h2>{p.title}</h2>{p.author&&<div className="lp-reply-author"><Avatar author src={p.author.avatar} size={25}/><span>{p.author.name}<small>{p.author.badge??p.author.expertise} · 来自本次公开文章检索</small></span></div>}{p.author?.matchReason&&<p className="lp-author-match">{p.author.matchReason}{p.author.coverageLimit&&<><br/>适用边界：{p.author.coverageLimit}</>}</p>}<div className="lp-answer-prose"><MarkdownMath source={p.text} sourceExcerpt={!!p.author}/></div>{p.author?.url&&<a className="lp-original-link" href={sourceLink(p.author.url).href} target="_blank" rel="noopener noreferrer">去知乎阅读这位博主的原文 ↗</a>}<div className="lp-answer-sources"><span>{p.author?'新博主观点':p.sources.length?'资料来源':'依据当前卡片'}</span>{p.sources.map(id=><SourceTag key={id} number={articles.findIndex(a=>a.id===id)+1} onClick={()=>onSource?.(id)}/>)}<button className="lp-locate-node" onClick={()=>onNode?.(p.id)}><Glyph name="graph" size={12}/>在脉络中查看</button></div></section>)}{message.text&&<div className="lp-plain-answer"><MarkdownMath source={message.text}/></div>}<ActivityList activities={message.activities??[]} completed/>{message.incomplete?<span className="lp-incomplete">已停止 · 未完成内容不会生成知识卡</span>:<div className="lp-answer-actions"><IconButton icon="copy" label="复制回答" onClick={()=>onCopy?.(message.paragraphs?.length?paragraphsMarkdown(message.paragraphs,articles):message.text??'')}/><span>{message.paragraphs?.length??0} 个内容片段</span></div>}</div></article>
}
export function ActivityList({activities,completed=false,waiting=false,part='all'}:{activities:TaskActivity[];completed?:boolean;waiting?:boolean;part?:'all'|'before'|'after'}) {
  const items=activities.filter(a=>part==='all'||(part==='after'?a.kind==='edit':a.kind!=='edit'))
  const done=items.filter(a=>a.status==='done'),active=items.filter(a=>a.status!=='done')
  if(!items.length)return null
  return <div className="lp-activities">
    {done.length>0&&<details className="lp-activity-history"><summary><Glyph name="check" size={13}/>{completed?'已完成':`已完成 ${done.length} 步`}</summary><div>{done.map(a=><div className="lp-activity-done" key={a.id}><Glyph name={a.kind==='edit'?'graph':'check'} size={13}/><span>{a.title}{a.detail&&<small>{a.detail}</small>}</span></div>)}</div></details>}
    {!completed&&active.map(a=><div key={a.id} className="lp-activity" data-activity={a.id}><StatusPill busy={!waiting&&a.status==='running'} waiting={waiting||a.status==='waiting'}>{waiting?`待继续 · ${a.title}`:a.title}</StatusPill>{a.detail&&<small>{a.detail}</small>}</div>)}
  </div>
}
export function ChatPanel({ conversation, selected, nodes, depth, onDepth, onRemove, onClear, onSend, onStop, mode, onMode, focusToken, phase, draft, busy, authorBusy, onSource, onNode, onCopy, onRetry, paused=false, task }: {conversation:Conversation;selected:string[];nodes:GraphNode[];depth:'fast'|'deep';onDepth:(d:'fast'|'deep')=>void;onRemove:(id:string)=>void;onClear:()=>void;onSend:(text:string)=>Promise<boolean>;onStop:()=>void;mode:'ai'|'author';onMode:(mode:'ai'|'author')=>void;focusToken:number;phase:Phase;draft:string;busy:boolean;authorBusy:boolean;onSource:(id:string)=>void;onNode:(id:string)=>void;onCopy:(text:string)=>void;onRetry:()=>void;paused?:boolean;task?:TaskView|null}) {
  const {concept}=useLearningData()
  const scroll=useRef<HTMLDivElement>(null),follow=useRef(conversation.messages.length<2),lastConversation=useRef(conversation.id)
  const waiting=task?.status==='waiting',visible=busy||waiting,activities=task?.activities??[]
  useEffect(()=>{if(busy)follow.current=true},[busy])
  useEffect(()=>{if(follow.current)scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:'instant' as ScrollBehavior})},[draft,conversation.messages.length,phase,activities,waiting])
  useEffect(()=>{if(lastConversation.current===conversation.id)return;lastConversation.current=conversation.id;follow.current=true;scroll.current?.scrollTo({top:scroll.current.scrollHeight})},[conversation.id])
  return <section className="lp-chat-panel" aria-label="学习对话">
    <div className="lp-chat-scroll" ref={scroll} onScroll={()=>{const el=scroll.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<90}}>
      {conversation.messages.map(m=><AnswerMessage key={m.id} message={m} onSource={onSource} onNode={onNode} onCopy={onCopy}/>)}
      {conversation.messages.length===0&&!visible&&<div className="lp-chat-empty lp-enter"><Avatar size={54}/><h2>换个角度，继续探索</h2><p>文章和知识脉络都在。<br/>从一个新问题开始吧。</p><div>{[`用一个例子解释${concept}`,'这些文章的观点有什么不同？'].map(q=><button key={q} onClick={()=>onSend(q)}>{q}<Glyph name="arrow" size={14}/></button>)}</div></div>}
      {visible&&<article className="lp-answer lp-pending-answer" data-task={task?.id}>
        <Avatar author={authorBusy} size={33}/><div className="lp-answer-content">
          <div className="lp-answer-name">{authorBusy?'寻找相关作者':'刘看山'}</div>
          <ActivityList activities={activities} waiting={waiting||task?.status==='queued'} part="before"/>
          {draft&&<div className="lp-streaming" aria-live="off"><MarkdownMath source={draft} streaming/></div>}
          <ActivityList activities={activities} waiting={waiting||task?.status==='queued'} part="after"/>
          {(!activities.length||task?.status==='queued')&&!waiting&&<StatusPill busy>{task?.phase??'正在准备回答'}</StatusPill>}
          {waiting&&<div className="lp-answer-paused" role="status"><p>这次讲解还没完成，已生成的内容保留在这里。</p>{task?.recoverable?<button className="lp-secondary" onClick={onRetry}>继续完成</button>:<span>本次重试次数已用完。</span>}<button className="lp-secondary" onClick={onStop}>停止本次任务</button></div>}
        </div>
      </article>}
    </div>
    <div className="lp-composer-area"><LearningComposer key={conversation.id} selected={selected} nodes={nodes} onRemove={onRemove} onClear={onClear} depth={depth} onDepth={onDepth} onSend={onSend} onStop={onStop} busy={busy} paused={paused} disabled={phase==='empty'||phase==='search-error'} mode={mode} onMode={onMode} focusToken={focusToken}/></div>
  </section>
}
