import {sourceLink} from './source-link'
import { KnowledgeMark } from '../ui/KnowledgeMark'
import { MarkdownMath } from '../lib/MarkdownMath'
import { memo, useCallback, useEffect, useMemo, useLayoutEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import type { GraphNode } from './model'
import { useLearningData } from './data'
import { NodePrompt, type NodePromptMode } from './NodePrompt'
import { Avatar, CountBadge, Glyph, IconButton, SourceTag, StatusPill } from './atoms'
type Point={x:number;y:number}
import { appendCustom, descendants, layoutTree, removeBranch,childrenByParent,offsetTree } from './tree'
import { KnowledgeDocument } from './Document'
import { NodeEditor, type EditorMode } from './NodeEditor'
export type PendingReply={id:string;mode:NodePromptMode;question:string;parents:string[];text:string;status?:string;waiting?:boolean;recoverable?:boolean}
type CardActions={onAsk?:()=>void;onAuthor?:()=>void;onCopy?:()=>void;onAdd?:()=>void;onColor?:()=>void;onMore?:()=>void;busy?:boolean;editing?:boolean;toolbar?:boolean;onFinishEdit?:(title:string)=>void}
export function NodeToolbar({onAsk,onAuthor,onCopy,onAdd,onColor,onMore,busy}:CardActions){return <div className="lp-node-toolbar" onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}>
  <IconButton icon="graph" label="添加卡片" disabled={busy} onClick={onAdd}/><IconButton icon="copy" label="复制节点内容" onClick={onCopy}/><IconButton icon="palette" label="卡片颜色和描边" disabled={busy} onClick={onColor}/><IconButton icon="more" label="更多卡片操作" disabled={busy} onClick={onMore}/><span/><button disabled={busy} onClick={e=>{e.currentTarget.focus();onAsk?.()}}><Glyph name="spark" size={15}/>询问 AI</button><button disabled={busy} onClick={e=>{e.currentTarget.focus();onAuthor?.()}}><Glyph name="message" size={15}/>问博主</button>
</div>}
// Matches the reference edit(): edit the title in place; blur/Enter/Escape commit.
function InlineTitle({title,onFinish}:{title:string;onFinish:(title:string)=>void}){
  const ref=useRef<HTMLSpanElement>(null),done=useRef(false)
  useLayoutEffect(()=>{const el=ref.current;if(!el)return;el.textContent=title;el.focus({preventScroll:true});const range=document.createRange();range.selectNodeContents(el);range.collapse(false);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range)},[])
  const finish=()=>{if(done.current)return;done.current=true;onFinish(ref.current?.innerText.trim()??title)}
  return <h3 className="lp-inline-title"><span ref={ref} contentEditable suppressContentEditableWarning role="textbox" aria-label="编辑卡片标题" onPointerDown={e=>e.stopPropagation()} onBlur={finish} onKeyDown={e=>{e.stopPropagation();if((e.key==='Enter'||e.key==='Escape')&&!e.nativeEvent.isComposing){e.preventDefault();finish()}}}/></h3>
}
export function GraphCard({node,selected=false,expanded=false,onExpand,onOriginal,onSource,editing,onFinishEdit,toolbar=true,...actions}:{node:GraphNode;selected?:boolean;expanded?:boolean;onExpand?:()=>void;onOriginal?:()=>void;onSource?:(id:string)=>void}&CardActions){ const {articles,concept:CONCEPT,example}=useLearningData(); return <div className={`lp-graph-card ${selected?'is-selected':''}`} data-type={node.type} data-custom-color={node.color?true:undefined} style={{background:node.color??'var(--surface-1)',borderWidth:node.stroke??1}}>
  {node.type!=='custom'&&<div className="lp-node-kind"><KnowledgeMark kind={node.type} size={17}/>{node.type==='root'?'学习概念':node.type==='article'?(example?(articles.find(a=>a.id===node.id)?.sourceKind==='web'?'论文阅读锚点':'知乎文章'):articles.find(a=>a.id===node.id)?.sourceKind==='upload'?'上传资料':articles.find(a=>a.id===node.id)?.sourceKind==='collection'?'知乎收藏':articles.find(a=>a.id===node.id)?.sourceKind==='web'?'全网资料':'知乎文章'):node.type==='author'?'新博主解读':example?'示例解读':'AI 回答'}{node.edited&&<span>· 已编辑</span>}{node.type==='article'&&<CountBadge>{articles.findIndex(a=>a.id===node.id)+1}</CountBadge>}</div>}
  {node.author&&<div className="lp-card-author"><Avatar author src={node.author.avatar} size={24}/><span><strong>{node.author.name}</strong><small>{node.author.expertise}</small></span></div>}
  {node.author&&node.title!==node.author.name&&<h3>{node.title}</h3>}{!node.author&&(editing?<InlineTitle title={node.title} onFinish={title=>onFinishEdit?.(title)}/>:<h3>{node.title||'\u00a0'}</h3>)}{node.author?<div className={`lp-author-content ${expanded?'is-expanded':''}`}>{node.author.matchReason&&<p className="lp-author-match">{node.author.matchReason}{node.author.coverageLimit&&<><br/>适用边界：{node.author.coverageLimit}</>}</p>}{node.text&&<MarkdownMath className="lp-node-prose" source={node.text} sourceExcerpt passive/>}</div>:node.text&&<MarkdownMath className={`lp-node-prose ${expanded?'is-expanded':''}`} source={node.text} sourceExcerpt={node.type==='article'&&!node.edited} passive/>}
  {node.type!=='root'&&node.type!=='custom'&&<><div className="lp-node-sources">{node.type==='author'?<>本次检索 · 博主文章{node.author?.url&&(onOriginal?<button className="lp-author-original" aria-expanded={expanded} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onOriginal()}}>{expanded?'收起文章':'阅读原文'}</button>:<a className="lp-author-original" href={sourceLink(node.author.url).href} target="_blank" rel="noopener noreferrer" onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()}>阅读原文 ↗</a>)}</>:node.origin==='direct'?'刘看山讲解':node.sources.length?<>{node.type==='article'?'资料':'资料来源'}{node.sources.map(id=>{const number=articles.findIndex(a=>a.id===id)+1;return number>0?<SourceTag key={id} number={number} onClick={()=>onSource?.(id)}/>:null})}</>:'依据父卡内容'}</div><button className="lp-node-expand" aria-expanded={expanded} onClick={e=>{e.stopPropagation();onExpand?.()}}>{expanded?'收起内容':node.type==='article'&&example?'展开阅读说明':node.type==='article'&&articles.find(a=>a.id===node.id)?.sourceKind!=='upload'?'展开完整总结':'展开完整正文'}<Glyph name="chevron" size={11}/></button></>}
  {selected&&!editing&&toolbar&&<NodeToolbar {...actions}/>}</div>}
function KnowledgeGraphView({ nodes, selected, onSelect, onSelection, onPromptSubmit, depth, onDepth, busy=false, submitError, initialPrompt=null, pending=[], onStop, onResume, onCopy, focusId, onSource, active=true, onChange, onUndo, onRedo, canUndo=false, canRedo=false, initialPresentation='map' }: { nodes:GraphNode[]; selected:string[]; onSelect:(id:string,additive:boolean)=>void; onSelection:(ids:string[])=>void; onPromptSubmit:(text:string,mode:NodePromptMode,ids:string[])=>Promise<boolean>; depth:'fast'|'deep';onDepth:(depth:'fast'|'deep')=>void;busy?:boolean;submitError?:string;initialPrompt?:NodePromptMode|null;pending?:PendingReply[];onStop:()=>void;onResume?:()=>void;onCopy:(text:string)=>void; focusId?:string|null;onSource?:(id:string)=>void;active?:boolean;onChange?:(nodes:GraphNode[])=>void;onUndo?:()=>void;onRedo?:()=>void;canUndo?:boolean;canRedo?:boolean;initialPresentation?:'map'|'document' }) {
  const [presentation,setPresentation]=useState<'map'|'document'>(initialPresentation),[docFocus,setDocFocus]=useState<string|null>(null),[docAnchor,setDocAnchor]=useState<{x:number;y:number;w:number;h:number}|null>(null)
  const stage=useRef<HTMLDivElement>(null),lastNodeClick=useRef<{id:string;at:number}|null>(null)
  const [prompt,setPrompt]=useState<{mode:NodePromptMode;anchorId:string;ids:string[]}|null>(()=>initialPrompt?{mode:initialPrompt,anchorId:selected[0]??'root',ids:[...selected]}:null)
  const [editor,setEditor]=useState<{mode:EditorMode;anchorId:string}|null>(null)
  const promptLayer=useRef<HTMLDivElement>(null)
  const [stageSize,setStageSize]=useState({width:600,height:500})
  useEffect(()=>{const el=stage.current;if(!el)return;const observer=new ResizeObserver(()=>setStageSize({width:el.clientWidth,height:el.clientHeight}));observer.observe(el);return()=>observer.disconnect()},[active])
  useEffect(()=>{if(!active){setPrompt(null);setEditor(null)}},[active])
  const selectionKey=selected.join('|')
  const previousSelection=useRef(selectionKey)
  useEffect(()=>{if(previousSelection.current!==selectionKey){setPrompt(null);setEditor(null)}previousSelection.current=selectionKey},[selectionKey])
  useEffect(()=>{if(!prompt&&!editor)return;const outside=(e:PointerEvent)=>{const target=e.target as HTMLElement;if(!promptLayer.current?.contains(target)&&!target.closest('.lp-node-toolbar')){setPrompt(null);setEditor(null)}};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[!!prompt,!!editor])
  function openPrompt(mode:NodePromptMode,anchorId:string){setEditor(null);setPrompt({mode,anchorId,ids:mode==='ai'&&selected.includes(anchorId)?[...selected]:[anchorId]})}
  function openEditor(mode:EditorMode,anchorId:string){if(busy)return;setPrompt(null);setEditor({mode,anchorId})}
  function change(next:GraphNode[],newId?:string){onChange?.(next);if(newId){setCollapsed(old=>old.filter(id=>id!==next.find(n=>n.id===newId)?.parents[0]));onSelection([newId]);setNewFocus(newId)}}
  const [editingId,setEditingId]=useState<string|null>(null)
  function addCard(kind:'child'|'sibling',anchorId:string,title='',text='',beginEdit=true){
    if(busy)return;const result=appendCustom(nodes,anchorId,kind,title,text);setPrompt(null);setEditor(null);change(result.nodes,result.node.id);if(presentation==='document')setDocFocus(result.node.id);else if(beginEdit)setEditingId(result.node.id)
  }
  function editCard(id:string){if(busy||id==='root')return;setPrompt(null);setEditor(null);onSelection([id]);setDocFocus(id);setPresentation('document')}
  const [newFocus,setNewFocus]=useState<string|null>(null)

  const [view,setView]=useState({x:35,y:30,scale:.6})
  const [offsets,setOffsets]=useState<Record<string,Point>>({})
  const [collapsed,setCollapsed]=useState<string[]>([])
  const [expanded,setExpanded]=useState<string[]>([])
  const [query,setQuery]=useState('')
  const [searchOpen,setSearchOpen]=useState(false)
  const [marquee,setMarquee]=useState<{x:number;y:number;w:number;h:number}|null>(null)
  const pointerClick=useRef(false)
  const pointer=useRef<{mode:'pan'|'node'|'select';id?:string;start:Point;origin:Point;additive:boolean;moved:boolean}|null>(null)
  const pendingKey=pending.map(p=>p.id).join('|')
  const layoutNodes=useMemo(()=>[...nodes,...pending.map(p=>({id:p.id,type:'answer' as const,title:p.question,text:'',parents:p.parents,sources:[]}))],[nodes,pendingKey])
  const children=useMemo(()=>childrenByParent(layoutNodes),[layoutNodes])
  const baseLayout=useMemo(()=>layoutTree(layoutNodes,collapsed,expanded,pending.map(p=>p.id)),[layoutNodes,collapsed,expanded])
  const places=useMemo(()=>offsetTree(baseLayout,children,offsets),[baseLayout,children,offsets])
  const visible=useMemo(()=>layoutNodes.filter(n=>places[n.id]),[layoutNodes,places])
  const fit=useCallback(()=>{const el=stage.current;if(!el||!visible.length)return;const ps=Object.values(places);const minX=Math.min(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y));const w=Math.max(...ps.map(p=>p.x+p.w))-minX,h=Math.max(...ps.map(p=>p.y+p.h))-minY;const scale=Math.min(1,(el.clientWidth-80)/w,(el.clientHeight-100)/h);setView({scale:Math.max(.02,scale),x:(el.clientWidth-w*scale)/2-minX*scale,y:(el.clientHeight-h*scale)/2-minY*scale})},[places,visible.length])
  const fitRef=useRef(fit);fitRef.current=fit
  const initialized=useRef(false)
  useEffect(()=>{if(!active||presentation==='document'||initialized.current)return;const frame=requestAnimationFrame(()=>{initialized.current=true;if(!focusId)fitRef.current()});return()=>cancelAnimationFrame(frame)},[active,presentation])
  const focus=useCallback((id:string)=>{const el=stage.current,p=places[id];if(!el||!p)return;const scale=Math.max(.1,Math.min(1,(el.clientWidth-70)/(p.w+100),(el.clientHeight-100)/(p.h+60)));setView({scale,x:el.clientWidth/2-(p.x+p.w/2)*scale,y:el.clientHeight/2-(p.y+p.h/2)*scale})},[places])
  useEffect(()=>{if(focusId&&active){setCollapsed([]);if(presentation==='document')setDocFocus(focusId);else setNewFocus(focusId)}},[focusId,active])
  useEffect(()=>{if(newFocus&&places[newFocus]){focus(newFocus);setNewFocus(null)}},[newFocus,places])
  useEffect(()=>{if(!pending.length||!active||presentation==='document')return;const current=pending[0];const el=stage.current,p=places[current.id];if(!el||!p)return;const group=[p,...current.parents.map(id=>places[id]).filter(Boolean)];const left=Math.min(...group.map(n=>n.x)),top=Math.min(...group.map(n=>n.y)),right=Math.max(...group.map(n=>n.x+n.w)),bottom=Math.max(...group.map(n=>n.y+n.h));const scale=Math.min(.9,(el.clientWidth-70)/(right-left),(el.clientHeight-100)/(bottom-top));setView({scale:Math.max(.02,scale),x:(el.clientWidth-(right-left)*scale)/2-left*scale,y:(el.clientHeight-(bottom-top)*scale)/2-top*scale})},[pendingKey,active])
  const zoom=(factor:number)=>{const el=stage.current;if(!el)return;setView(v=>{const scale=Math.min(1.8,Math.max(.02,v.scale*factor));const x=el.clientWidth/2,y=el.clientHeight/2;return{scale,x:x-(x-v.x)*scale/v.scale,y:y-(y-v.y)*scale/v.scale}})}
  function local(e:ReactPointerEvent){const r=stage.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  function down(e:ReactPointerEvent,id?:string){if(e.button!==0)return;const target=e.target as HTMLElement;if(target.closest('button,a,input,textarea,[contenteditable=true],[role=dialog]'))return;e.preventDefault();e.stopPropagation();stage.current?.setPointerCapture(e.pointerId);pointer.current={mode:id?'node':e.shiftKey?'select':'pan',id,start:local(e),origin:id?(offsets[id]??{x:0,y:0}):{x:view.x,y:view.y},additive:e.metaKey||e.ctrlKey||e.shiftKey,moved:false};if(!id&&e.shiftKey){const p=local(e);setMarquee({...p,w:0,h:0})}}
  function move(e:ReactPointerEvent){const d=pointer.current;if(!d)return;const p=local(e),dx=p.x-d.start.x,dy=p.y-d.start.y;if(Math.abs(dx)+Math.abs(dy)>4)d.moved=true;if(d.mode==='pan')setView(v=>({...v,x:d.origin.x+dx,y:d.origin.y+dy}));else if(d.mode==='node'&&d.id&&d.moved)setOffsets(o=>({...o,[d.id!]:{x:d.origin.x+dx/view.scale,y:d.origin.y+dy/view.scale}}));else if(d.mode==='select')setMarquee({x:Math.min(p.x,d.start.x),y:Math.min(p.y,d.start.y),w:Math.abs(dx),h:Math.abs(dy)})}
  function up(e:ReactPointerEvent){const d=pointer.current;if(!d)return;pointer.current=null;pointerClick.current=true;requestAnimationFrame(()=>{pointerClick.current=false});if(d.mode==='node'&&d.id&&!d.moved){onSelect(d.id,d.additive);const now=performance.now(),last=lastNodeClick.current;if(!d.additive&&last?.id===d.id&&now-last.at<400){lastNodeClick.current=null;editCard(d.id)}else lastNodeClick.current={id:d.id,at:now};}else if(d.mode==='pan'&&!d.moved)onSelection([]);else if(d.mode==='select'&&marquee){const ids=visible.filter(n=>{const p=places[n.id],x=p.x*view.scale+view.x,y=p.y*view.scale+view.y;return x+p.w*view.scale>=marquee.x&&x<=marquee.x+marquee.w&&y+p.h*view.scale>=marquee.y&&y<=marquee.y+marquee.h}).map(n=>n.id);onSelection(ids)}setMarquee(null);if(stage.current?.hasPointerCapture(e.pointerId))stage.current.releasePointerCapture(e.pointerId)}
  useEffect(()=>{const el=stage.current;if(!el)return;const prevent=(e:WheelEvent)=>{if(!(e.target as HTMLElement).closest('.lp-node-prompt-layer,.lp-doc-view'))e.preventDefault()};el.addEventListener('wheel',prevent,{passive:false});return()=>el.removeEventListener('wheel',prevent)},[active])
  const matches=(presentation==='document'?nodes:visible).filter(n=>query.trim()&&(n.title+n.text).includes(query.trim()))
  const promptWidth=Math.min(editor?.mode==='add'||editor?.mode==='more'?220:prompt?.mode==='author'?360:320,stageSize.width-24),promptHeight=Math.min(editor?.mode==='add'?100:editor?.mode==='more'?180:editor?210:prompt?.mode==='ai'?330:268,stageSize.height-24)
  const anchorId=prompt?.anchorId??editor?.anchorId??selected.at(-1)
  const anchor=presentation==='document'?docAnchor:anchorId?places[anchorId]:null
  const isDoc=presentation==='document'
  function updateDocAnchor(){const r=stage.current?.getBoundingClientRect(),el=Array.from(stage.current?.querySelectorAll<HTMLElement>('[data-doc-id]')??[]).find(e=>e.dataset.docId===anchorId),b=el?.getBoundingClientRect();setDocAnchor(r&&b?{x:b.left-r.left,y:b.top-r.top,w:b.width,h:b.height}:null)}
  useLayoutEffect(()=>{if(isDoc)updateDocAnchor()},[isDoc,anchorId,editor?.mode,prompt?.mode])
  const toolbarNode=nodes.find(node=>node.id===selected.at(-1))
  const toolbarAnchor=toolbarNode?(isDoc?docAnchor:places[toolbarNode.id]):null
  const toolbarWidth=Math.min(346,stageSize.width-24),toolbarHeight=toolbarWidth<330?80:44
  const toolbarLeft=toolbarAnchor?Math.max(12,Math.min(stageSize.width-toolbarWidth-12,isDoc?toolbarAnchor.x:view.x+toolbarAnchor.x*view.scale)):12
  const toolbarBelow=toolbarAnchor?view.y+(toolbarAnchor.y+toolbarAnchor.h)*view.scale+12:12
  const toolbarTop=isDoc?Math.max(12,stageSize.height-toolbarHeight-16):toolbarAnchor?Math.max(12,Math.min(stageSize.height-toolbarHeight-48,toolbarBelow+toolbarHeight<stageSize.height-48?toolbarBelow:view.y+toolbarAnchor.y*view.scale-toolbarHeight-12)):12
  const editNode=nodes.find(n=>n.id===editor?.anchorId)
  const anchorX=anchor?isDoc?anchor.x:view.x+anchor.x*view.scale:12,anchorY=anchor?isDoc?anchor.y:view.y+anchor.y*view.scale:12
  const anchorRight=anchor?anchorX+anchor.w*(isDoc?1:view.scale):12,anchorBottom=anchor?anchorY+anchor.h*(isDoc?1:view.scale):12
  const promptBeside=!editor&&anchorRight+14+promptWidth<=stageSize.width-12
  const promptLeft=Math.max(12,Math.min(stageSize.width-promptWidth-12,promptBeside?anchorRight+14:anchorX))
  const desiredTop=promptBeside?anchorY:anchorBottom+48+promptHeight<=stageSize.height-12?anchorBottom+48:anchorY-promptHeight-12
  const promptTop=Math.max(12,Math.min(stageSize.height-promptHeight-12,desiredTop))
  if(!active)return null
  return <div className="lp-graph-panel"><header className="lp-graph-header"><div><div className="lp-presentation-tabs" aria-label="知识脉络呈现方式"><IconButton icon="graph" label="画布模式" active={!isDoc} onClick={()=>{setPrompt(null);setEditor(null);setPresentation('map');if(selected[0])setNewFocus(selected[0])}}/><IconButton icon="document" label="文档模式" active={isDoc} onClick={()=>{setPrompt(null);setEditor(null);setPresentation('document');setDocFocus(null)}}/></div><strong>知识脉络</strong><span>{nodes.length} 个节点{pending.length?' · 正在生成':''}</span></div><div>{pending.length>0&&<IconButton icon="stop" label="停止本次生成" onClick={onStop}/>}<IconButton icon="undo" label="撤销" disabled={!canUndo||busy} onClick={onUndo}/><IconButton icon="redo" label="重做" disabled={!canRedo||busy} onClick={onRedo}/><IconButton icon="graph" label="添加想法卡片" disabled={busy} onClick={()=>addCard('child',selected[0]??'root')}/><IconButton icon="search" label="搜索画布" active={searchOpen} onClick={()=>setSearchOpen(!searchOpen)}/>{!isDoc&&<><IconButton icon="plus" label="放大画布" onClick={()=>zoom(1.2)}/><IconButton icon="minus" label="缩小画布" onClick={()=>zoom(1/1.2)}/><IconButton icon="fit" label="适应全部节点" onClick={fit}/></>}</div></header>
    {searchOpen&&<div className="lp-graph-find"><Glyph name="search" size={15}/><input autoFocus aria-label="搜索节点内容" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索节点内容" onKeyDown={e=>{if(e.key==='Enter'&&matches[0]){if(isDoc){onSelection([matches[0].id]);setDocFocus(matches[0].id)}else focus(matches[0].id)};if(e.key==='Escape'){setSearchOpen(false);setQuery('')}}}/><span role="status" aria-live="polite">{matches.length} 项</span><IconButton icon="close" label="关闭画布搜索" onClick={()=>{setSearchOpen(false);setQuery('')}}/></div>}
    <div className="lp-graph-stage" ref={stage} tabIndex={0} aria-label="知识脉络画布，Shift 拖动框选，点击选择节点" onContextMenu={e=>{e.preventDefault();const id=(e.target as HTMLElement).closest<HTMLElement>('[data-node-id]')?.dataset.nodeId;if(id){onSelection([id]);openEditor('more',id)}}} onPointerDown={e=>down(e)} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{pointer.current=null;setMarquee(null)}} onWheel={e=>{if(e.ctrlKey||e.metaKey){zoom(e.deltaY<0?1.07:1/1.07)}else setView(v=>({...v,x:v.x-e.deltaX,y:v.y-e.deltaY}))}} onKeyDown={e=>{if((e.target as HTMLElement).closest('button,a,input,textarea,select,[contenteditable=true],[role=dialog],.lp-doc-view'))return;
      if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(!busy)(e.shiftKey?onRedo:onUndo)?.();return}
      if(selected.length===1&&!busy){const id=selected[0];if(e.key==='Tab'){e.preventDefault();addCard('child',id);return}if(e.key==='Enter'&&id!=='root'){e.preventDefault();editCard(id);return}if(e.key==='F2'&&id!=='root'){e.preventDefault();editCard(id);return}if((e.key==='Delete'||e.key==='Backspace')&&id!=='root'&&nodes.find(n=>n.id===id)?.type!=='article'){e.preventDefault();change(removeBranch(nodes,id));onSelection([]);return}}
      if(e.key==='Escape'){onSelection([]);setSearchOpen(false)}if(e.key==='0')fit();if(e.key==='+'||e.key==='=')zoom(1.2);if(e.key==='-')zoom(1/1.2);const d:{[key:string]:Point}={ArrowRight:{x:-50,y:0},ArrowLeft:{x:50,y:0},ArrowUp:{x:0,y:50},ArrowDown:{x:0,y:-50}};if(d[e.key]){e.preventDefault();setView(v=>({...v,x:v.x+d[e.key].x,y:v.y+d[e.key].y}))}}}>
      <div className="lp-graph-world" hidden={isDoc} style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.scale})`}}><svg className="lp-edges" width="1" height="1" aria-hidden="true">{visible.flatMap(n=>n.parents.filter(id=>places[id]&&!collapsed.includes(id)).map(id=>{const a=places[id],b=places[n.id];const x=a.x+a.w,y=a.y+a.h/2,tx=b.x,ty=b.y+b.h/2;return <path key={`${id}-${n.id}`} data-parent-id={id} data-child-id={n.id} className={selected.includes(n.id)||selected.includes(id)?'is-active':''} d={`M ${x} ${y} H ${(x+tx)/2} V ${ty} H ${tx}`}/>}))}</svg>
      {visible.map(n=>{const p=places[n.id],kids=children.get(n.id)??[];const current=pending.find(p=>p.id===n.id);if(current)return <div className="lp-pending-card" key={n.id} data-pending-id={n.id} style={{left:p.x,top:p.y,width:p.w,minHeight:p.h}} onPointerDown={e=>e.stopPropagation()}><StatusPill busy={!current.waiting} waiting={current.waiting}>{current.status??(current.mode==='author'?'寻找新的相关博主':'AI 回复生成中')}</StatusPill><h3>{current.question}</h3><p>{current.text||(current.waiting?'已有进度已保留，可继续或停止本次任务。':'正在阅读当前卡片，准备回复…')}</p>{current.waiting&&current.recoverable&&<button onClick={onResume}>继续完成</button>}<button onClick={onStop}><Glyph name="stop" size={12}/>停止生成</button></div>;return <div className={`lp-node ${matches.some(m=>m.id===n.id)?'is-match':''}`} key={n.id} data-node-id={n.id} data-parent-id={n.parents[0]} style={{left:p.x,top:p.y,width:p.w,height:p.h,zIndex:selected.includes(n.id)?3:1}} tabIndex={0} role="group" aria-roledescription="知识卡片" onFocus={event=>{const target=event.target as HTMLElement;if(!target.matches(':focus-visible'))return;const bounds=target.getBoundingClientRect(),viewport=stage.current?.getBoundingClientRect();if(target===event.currentTarget||viewport&&(bounds.left<viewport.left||bounds.right>viewport.right||bounds.top<viewport.top||bounds.bottom>viewport.bottom))focus(n.id)}} aria-label={`${n.type==='article'?'文章节点':n.type==='root'?'概念根节点':n.type==='custom'?'自定义卡片':'回答节点'}：${n.title||'空白卡片'}${selected.includes(n.id)?'，已选中':''}`} onClick={e=>{if(!pointerClick.current&&!(e.target as HTMLElement).closest('button,a,[contenteditable=true]'))onSelect(n.id,e.shiftKey||e.metaKey||e.ctrlKey)}} onPointerDown={e=>down(e,n.id)} onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('button,a,[contenteditable=true]'))editCard(n.id)}} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key===' '||(e.key==='Enter'&&!selected.includes(n.id))){e.stopPropagation();e.preventDefault();onSelect(n.id,e.shiftKey||e.metaKey)}}}><GraphCard node={n} toolbar={false} selected={selected.includes(n.id)} expanded={expanded.includes(n.id)} onExpand={()=>setExpanded(old=>old.includes(n.id)?old.filter(id=>id!==n.id):[...old,n.id])} onAsk={()=>openPrompt('ai',n.id)} onAuthor={()=>openPrompt('author',n.id)} onCopy={()=>onCopy(n.title+'\n'+n.text)} onSource={onSource} onAdd={()=>openEditor('add',n.id)} onColor={()=>openEditor('color',n.id)} onMore={()=>openEditor('more',n.id)} busy={busy} editing={editingId===n.id} onFinishEdit={title=>{change(nodes.map(item=>item.id===n.id?{...item,title,edited:item.type==='custom'?undefined:true}:item));setEditingId(null)}}/>{kids.length>0&&<button className="lp-node-toggle" aria-label={`${collapsed.includes(n.id)?'展开':'收起'} ${n.title} 的分支`} onPointerDown={e=>e.stopPropagation()} onClick={()=>setCollapsed(old=>old.includes(n.id)?old.filter(id=>id!==n.id):[...old,n.id])}>{collapsed.includes(n.id)?kids.length:<Glyph name="minus" size={10}/>}</button>}</div>})}</div>
      {toolbarNode&&toolbarAnchor&&(isDoc||editingId!==toolbarNode.id)&&<div className={`lp-map-toolbar ${isDoc?'is-document':''}`} style={{left:toolbarLeft,top:toolbarTop,width:toolbarWidth}}><NodeToolbar busy={busy} onAsk={()=>openPrompt('ai',toolbarNode.id)} onAuthor={()=>openPrompt('author',toolbarNode.id)} onCopy={()=>onCopy(toolbarNode.title+'\n'+toolbarNode.text)} onAdd={()=>openEditor('add',toolbarNode.id)} onColor={()=>openEditor('color',toolbarNode.id)} onMore={()=>openEditor('more',toolbarNode.id)}/></div>}
      {isDoc&&<KnowledgeDocument nodes={pending.length?[...nodes,...pending.map(p=>({id:p.id,type:'answer' as const,title:p.question,text:p.text||p.status||'正在阅读当前卡片…',parents:p.parents,sources:[]}))]:nodes} selected={selected} focusId={docFocus} busy={busy} onSelect={id=>{if(!selected.includes(id))onSelection([id])}} onSave={(id,title,text)=>{change(nodes.map(n=>n.id===id?{...n,title,text,edited:true}:n))}} onScroll={updateDocAnchor} renderToolbar={()=>null}/> }
      {prompt&&anchor&&<div ref={promptLayer} className="lp-node-prompt-layer" style={{left:promptLeft,top:promptTop,width:promptWidth,maxHeight:promptHeight}}><NodePrompt onStop={onStop} mode={prompt.mode} nodes={prompt.ids.map(id=>nodes.find(n=>n.id===id)).filter((n):n is GraphNode=>!!n)} depth={depth} onDepth={onDepth} busy={busy} submitError={submitError} onClose={()=>setPrompt(null)} onSubmit={async text=>{setCollapsed(old=>old.filter(id=>!prompt.ids.includes(id)));const sent=await onPromptSubmit(text,prompt.mode,prompt.ids);if(sent)setPrompt(current=>current===prompt?null:current);return sent}}/></div>}
      {editor&&editNode&&anchor&&<div ref={promptLayer} className="lp-node-prompt-layer" style={{left:promptLeft,top:promptTop,width:promptWidth,maxHeight:promptHeight}}><NodeEditor key={`${editor.anchorId}-${editor.mode}`} mode={editor.mode} node={editNode} onMode={mode=>setEditor({...editor,mode})} onClose={()=>setEditor(null)}
        onAdd={kind=>addCard(kind,editNode.id)} onEdit={()=>editCard(editNode.id)}
        onColor={color=>change(nodes.map(n=>(selected.includes(editNode.id)?selected.includes(n.id):n.id===editNode.id)?{...n,color}:n))}
        onStroke={stroke=>change(nodes.map(n=>(selected.includes(editNode.id)?selected.includes(n.id):n.id===editNode.id)?{...n,stroke}:n))}
        onDuplicate={()=>addCard('sibling',editNode.id,editNode.title,editNode.text,false)}
        onDelete={()=>{change(removeBranch(nodes,editNode.id));onSelection([]);setEditor(null)}}/></div>}
      {marquee&&<div className="lp-marquee" style={{left:marquee.x,top:marquee.y,width:marquee.w,height:marquee.h}}/>}
    </div>{!isDoc&&<div className="lp-graph-bottom"><span><i/>概念<span className="lp-legend-article"/>文章<span className="lp-legend-answer"/>回答</span><span>Shift 多选 · Tab 添加 · 双击编辑</span><button onClick={fit}>{Math.round(view.scale*100)}%</button></div>}
  </div>
}

export const KnowledgeGraph=memo(KnowledgeGraphView,(old,next)=>{
  if(old.active||next.active)return false
  return old.nodes===next.nodes&&old.selected===next.selected&&old.focusId===next.focusId
})
