import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {build} from 'vite';
import react from '@vitejs/plugin-react';
import postcss from 'postcss';

const root = fileURLToPath(new URL('../', import.meta.url));
const local = file => path.join(root, file);
const portable = file => path.relative(root, file).split(path.sep).join('/');
const runtimeAssets = new Set(['assets/images/illustrations/threadpeak-icon.png']);
const rawTextAssets = new Set();
const content = {};
const assetHelper = local('src/runtime/assets.ts');
const extensions = /\.(?:svg|png|jpe?g|webp|gif|riv|wasm|glb|woff2?|ttf)$/;
const mime = {'.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.riv':'application/octet-stream','.wasm':'application/wasm','.glb':'model/gltf-binary','.woff2':'font/woff2','.woff':'font/woff','.ttf':'font/ttf'};
const vendorGlobals = {
  'react': 'React',
  'react-dom': 'ReactDOM',
  'react-dom/client': 'ReactDOM',
  'react/jsx-runtime': 'jsxRuntime',
  'react/jsx-dev-runtime': 'jsxRuntime',
  'three': 'THREE',
  'katex': 'katex',
  'remotion': 'Remotion',
  '@remotion/player': 'RemotionPlayer',
};
const write = async (file, data) => {
  await fs.mkdir(path.dirname(local(file)), {recursive:true});
  await fs.writeFile(local(file), data);
};
function collectPaths(value) {
  if (typeof value === 'string' && value.startsWith('assets/')) runtimeAssets.add(value);
  else if (value && typeof value === 'object') Object.values(value).forEach(collectPaths);
}
function assertNoEmbeddedMedia(code, fileName) {
  if (/data:(?:image\/[\w.+-]+|font\/[\w.+-]+|application\/wasm|model\/gltf-binary)[;,][^"'`]{80}/.test(code)) {
    console.error('Embedded prefixes:',[...code.matchAll(/data:(?:image|font|application\/wasm|model\/gltf-binary)[^"'`]{0,120}/g)].map(match=>match[0]));
    throw new Error('Asset bytes leaked into application code: ' + fileName);
  }
}
const shared = {
  root, configFile:false, envDir:false, publicDir:false, base:'./',
  define:{'process.env.NODE_ENV':JSON.stringify('production')},
};

const vendorResult = await build({
  ...shared,
  build:{
    write:false, target:'es2022', minify:true, cssMinify:false, modulePreload:false,
    assetsInlineLimit:0, cssCodeSplit:false, reportCompressedSize:false,
    rollupOptions:{
      input:local('src/runtime/vendor.ts'),
      output:{format:'iife', entryFileNames:'vendor.js'},
    },
  },
});
const vendorOutputs = (Array.isArray(vendorResult) ? vendorResult : [vendorResult]).flatMap(item => item.output);
for (const output of vendorOutputs) {
  if (output.type !== 'chunk') continue;
  assertNoEmbeddedMedia(output.code, output.fileName);
  await write('runtime/vendor.js', '// Third-party libraries only (React, Three.js, Remotion, KaTeX). Source is node_modules; do not edit this file.\n' + output.code);
}

const result = await build({
  ...shared,
  plugins:[{
    name:'local-product-resources', enforce:'pre',
    resolveId(source, importer) {
      if (source.endsWith('.json') && importer) {
        const resolved = path.resolve(path.dirname(importer), source);
        if (resolved.startsWith(local('src/data/'))) return '\0product-content:' + resolved + '.js';
      }
    },
    async load(id) {
      if (id.startsWith('\0product-content:')) {
        const file = id.slice('\0product-content:'.length, -3);
        const key = path.basename(file, '.json');
        const data = JSON.parse(await fs.readFile(file, 'utf8'));
        content[key] = data;
        collectPaths(data);
        return `import {resolveAssetReferences} from ${JSON.stringify(assetHelper)};export default resolveAssetReferences(window.__PRODUCT_DATA__[${JSON.stringify(key)}]);`;
      }
      const [file, query] = id.split('?');
      if (!file.startsWith(local('assets/')) || !extensions.test(file)) return;
      const key = portable(file);
      runtimeAssets.add(key);
      if (query === 'raw') rawTextAssets.add(key);
      const helper = query === 'raw' ? 'assetText' : 'assetUrl';
      return `import {${helper}} from ${JSON.stringify(assetHelper)};export default ${helper}(${JSON.stringify(key)});`;
    },
  }, react()],
  build:{
    write:false, target:'es2022', minify:true, cssMinify:false, modulePreload:false,
    assetsInlineLimit:0, cssCodeSplit:false, reportCompressedSize:false,
    rollupOptions:{
      input:local('src/app/main.tsx'),
      external:Object.keys(vendorGlobals),
      output:{
        format:'iife',
        name:'ThreadPeakProduct',
        entryFileNames:'product.js',
        assetFileNames:'[name][extname]',
        globals:vendorGlobals,
      },
    },
  },
});
const outputs = (Array.isArray(result) ? result : [result]).flatMap(item => item.output);
let css = '';
for (const output of outputs) {
  if (output.type === 'chunk') {
    assertNoEmbeddedMedia(output.code, output.fileName);
    const banner = output.fileName === 'product.js' ? '// ThreadPeak product page. Edit src/, then run npm run build.\n' : '';
    await write('runtime/' + output.fileName, banner + output.code);
  } else if (output.fileName.endsWith('.css')) css += String(output.source);
  else {
    const file = 'assets/fonts/' + path.basename(output.fileName);
    await write(file, output.source);
    runtimeAssets.add(file);
  }
}

const parsed = postcss.parse(css);
const fontRules = [];
parsed.walkAtRules('font-face', rule => {fontRules.push(rule.toString());rule.remove();});
let fonts = fontRules.join('\n\n').replace(/url\((['"]?)([^)'"\s]+)\1\)/g, (_, quote, url) => {
  if (url.startsWith('data:')) throw new Error('Font was unexpectedly inlined');
  const file = 'assets/fonts/' + path.basename(url);
  runtimeAssets.add(file);
  return `url("../${file}")`;
});
await write('styles/product.css', parsed.toString());
await write('styles/fonts.css', fonts + '\n');

const files = {};
const groups = {images:{},lettering:{},characters:{},models:{}};
for (const file of [...runtimeAssets].sort()) {
  const bytes = await fs.readFile(local(file));
  const type = mime[path.extname(file)] ?? 'application/octet-stream';
  const uri = `data:${type};base64,${bytes.toString('base64')}`;
  const group = file.startsWith('assets/fonts/') ? 'fonts'
    : file.startsWith('assets/models/') ? 'models'
    : /assets\/(rive|wasm)\//.test(file) ? 'characters'
    : file.startsWith('assets/lettering/') ? 'lettering' : 'images';
  if (group !== 'fonts') groups[group][file] = uri;
  else fonts = fonts.split(`"../${file}"`).join(JSON.stringify(uri));
  files[file] = {mime:type,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),offlineFile:group==='fonts'?'assets/offline/fonts.css':`assets/offline/${group}.js`};
}
const packs = [];
for (const [group, values] of Object.entries(groups)) {
  const file = `assets/offline/${group}.js`;
  await write(file, '// Generated asset data only. Edit the original files in assets/, then run npm run build.\n'
    + 'Object.assign(window.__PRODUCT_ASSETS__ ||= Object.create(null),'
    + JSON.stringify(values) + ');\n');
  packs.push('./' + file);
}
await write('assets/offline/fonts.css', fonts + '\n');
await write('data/demo-content.js', '// Generated demonstration content; edit src/data/*.json.\nwindow.__PRODUCT_DATA__ = '
  + JSON.stringify(content) + ';\n');
let bootstrap = await fs.readFile(local('src/runtime/bootstrap.js'),'utf8');
bootstrap = bootstrap.replace('/* BUILD_OFFLINE_PACKS */ []',JSON.stringify(packs,null,2))
  .replace('/* BUILD_RAW_TEXT_FILES */ []',JSON.stringify([...rawTextAssets],null,2));
await write('runtime/bootstrap.js',bootstrap);
await write('index.html',`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#ffffff">
  <title>从目标出发，把知乎上的学习路线接到自己身上 · 问山 ThreadPeak</title>
  <link rel="icon" href="./assets/images/illustrations/threadpeak-icon.png">
  <link rel="stylesheet" href="./styles/product.css">
  <script defer src="./runtime/bootstrap.js"></script>
</head>
<body>
  <div id="root"></div>
  <noscript>请启用 JavaScript，以浏览完整的互动产品介绍。</noscript>
</body>
</html>
`);
await write('assets/manifest.json',JSON.stringify({generatedAt:new Date().toISOString(),files,rawTextFiles:[...rawTextAssets],offlinePacks:packs},null,2)+'\n');
const vendorBytes = (await fs.stat(local('runtime/vendor.js'))).size;
const productBytes = (await fs.stat(local('runtime/product.js'))).size;
console.log(`Built vendor ${vendorBytes} bytes, product ${productBytes} bytes, ${Object.keys(content).length} content modules and ${runtimeAssets.size} local assets.`);
